serviceMaps:
  serviceName: Notice-services
  mappings:
  - version: 1.0
    description: Persists assessment details to eg_pt_asmt_assessment table
    fromTopic: save-pt-notice
    isTransaction: true
    queryMaps:

    - query: INSERT INTO eg_pt_notice(noticeType,tenantId,uuid,noticeNumber,name,address,propertyId,assessmentYear,acknowledgementNumber,dateOfAnnualRet,entryDate,entryTime,place,resolutionon,dated,designation,authorisedpersonname,mobilenumber,penaltyamount,appealno,createdby, createdtime, lastmodifiedby, lastmodifiedtime, rule_23, rule_33, rule_34, rule_36, failedto_produce_necessary_documents, willfully_furnishes_incorrect_information, obstruct_any_authority_appointed) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);
      basePath: $.Notice
      jsonMaps:

      - jsonPath: $.Notice.noticeType

      - jsonPath: $.Notice.tenantId

      - jsonPath: $.Notice.noticeuuid

      - jsonPath: $.Notice.noticeNumber

      - jsonPath: $.Notice.name

      - jsonPath: $.Notice.address

      - jsonPath: $.Notice.propertyId

      - jsonPath: $.Notice.assessmentYear

      - jsonPath: $.Notice.acknowledgementNumber

      - jsonPath: $.Notice.dateOfAnnualRet

      - jsonPath: $.Notice.entryDate

      - jsonPath: $.Notice.entryTime

      - jsonPath: $.Notice.place

      - jsonPath: $.Notice.resolutionOn

      - jsonPath: $.Notice.dated

      - jsonPath: $.Notice.designation

      - jsonPath: $.Notice.authorisedpersonName

      - jsonPath: $.Notice.mobilenumber

      - jsonPath: $.Notice.penaltyAmount

      - jsonPath: $.Notice.appealNo
      
      - jsonPath: $.Notice.auditDetails.createdBy

      - jsonPath: $.Notice.auditDetails.createdTime

      - jsonPath: $.Notice.auditDetails.lastModifiedBy

      - jsonPath: $.Notice.auditDetails.lastModifiedTime
      
      - jsonPath: $.Notice.Rule_23
      
      - jsonPath: $.Notice.Rule_33
      
      - jsonPath: $.Notice.Rule_34
      
      - jsonPath: $.Notice.Rule_36
      
      - jsonPath: $.Notice.FailedtoProduceNecessaryDocuments
      
      - jsonPath: $.Notice.WillfullyfurnishesIncorrectInformation
      
      - jsonPath: $.Notice.ObstructAnyAuthorityAppointed



    - query: INSERT INTO eg_pt_notice_comment (uuid,noticeid,comment,createdby, createdtime, lastmodifiedby, lastmodifiedtime, particulars, asperreturnfiled, aspermunicipality, remarks) VALUES (?,?,?,?,?,?,?,?,?,?,?);
      basePath: Notice.NoticeComment.*
      jsonMaps:

      - jsonPath: $.Notice.NoticeComment.*.uuid

      - jsonPath: $.Notice.noticeuuid

      - jsonPath: $.Notice.NoticeComment.*.comment
      
      - jsonPath: $.Notice.NoticeComment.*.auditDetails.createdBy

      - jsonPath: $.Notice.NoticeComment.*.auditDetails.createdTime

      - jsonPath: $.Notice.NoticeComment.*.auditDetails.lastModifiedBy

      - jsonPath: $.Notice.NoticeComment.*.auditDetails.lastModifiedTime
      
      - jsonPath: $.Notice.NoticeComment.*.particulars
      
      - jsonPath: $.Notice.NoticeComment.*.asPerReturnFiled
      
      - jsonPath: $.Notice.NoticeComment.*.asPerMunicipality
      
      - jsonPath: $.Notice.NoticeComment.*.remarks
      
      
      
  - version: 1.0
    description: Updates Notice details to eg_pt_notice table
    fromTopic: update-pt-notice
    isTransaction: true
    queryMaps:
    
    
    - query: UPDATE eg_pt_notice SET penaltyamount=? WHERE propertyId=? AND noticetype=? AND tenantid=?;
      basePath: $.Notice
      jsonMaps:
      
      - jsonPath: $.Notice.penaltyAmount
      
      - jsonPath: $.Notice.propertyId
      
      - jsonPath: $.Notice.noticeType
      
      - jsonPath: $.Notice.tenantId

      

      


